version: 2
jobs:
  build:
    working_directory: ~/working_directory
    docker:
      - image: circleci/node:8-browsers
        env:
          - DISPLAY=:99
          - CHROME_BIN=/usr/bin/google-chrome
    steps:
      - checkout
      - run:
          name: Print system information
          command: |
            echo "node $(node -v)"
            echo "npm v$(npm --version)"
            echo "Yarn v$(yarn --version)"
            echo "$(google-chrome --version)"
      - run:
          name: Install coveralls and gulp globally
          command: sudo yarn global add coveralls gulp

      - deploy:
          name: Deployment
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              mkdir -p ~/artifacts
              ./scripts/nightly.sh $CIRCLE_BUILD_NUM $CIRCLE_SHA1 ~/artifacts
            fi
      - store_artifacts:
          path: ~/artifacts
